### ISSUE TITLE
Empty response, no connection

### ISSUE THREAD

**Issue by andrewmfiorillo** [mrtazz/restclient-cpp#70]
Hi!

I'm using a slightly modified version of the advanced example from the README and having issues getting off the ground. Specifically, the response object returned from `conn -> post(...)` comes back instantly with code 500 and an empty body. The server it's supposed to be talking to receives no requests.

The code I'm using looks like this
```
Proxy::Proxy(Proxy::Settings settings)
{
    // parse settings
    RestClient::init();
}

Proxy::~Proxy()
{
    RestClient::disable();
}

// requests are handled by a thread pool
Proxy::Request(...)
{
    // translate end-user request for back-end server
    std::string workerAddress; // address to back-end server, no trailing slash
    std::string payload; // json string with escaped quotes
    
    std::unique_ptr<RestClient::Connection> conn(new RestClient::Connection(workerAddress));
    conn->SetTimeout(1);
    RestClient::HeaderFields headers;
    headers["Content-Type"] = "application/json";
    conn->SetHeaders(headers);
    RestClient::Response r = conn->post("/", payload);

    // translate r back to what the end-user wants
}
```

### Environment and debugging details

- Using VS2015 Community on Windows 7
- libcurl version 7.52.0 built with [blackrosezy's batch file](https://github.com/blackrosezy/build-libcurl-windows)

Thanks for any help in the right direction!

**Comment by andrewmfiorillo** [comment]
Quick Update:

I tried a simpler version to check if it's my use case, though the same issue (empty body, code 500, no sign of life from recipient of request) occurs. My new test case look like

```
int main(int argc, char *argv[], char *envp[])
{
    RestClient::Response r = RestClient::post("http://127.0.0.1:8001/", "application/json", "invalid json");
    // I would expect this to come back as a 500, but with some error message produced by the recipient
    std::cout << "body: " << r.body << std::endl;
    std::cout << "code: " << r.code << std::endl;
}
```

**Comment by mrtazz** [comment]
@andrewmfiorillo can you post the diagnostics information gotten from `conn->GetInfo()`?

**Comment by andrewmfiorillo** [comment]
Can do!

```
baseUrl: http://6fmkd42:8001
basicAuth (usr,pass): (,)
certPath:
certType:
userAgent: foo/bar
followRedirects: 0
keyPath:
noSignal: 0
timeout: 1
lastRequest:
    appConnectTime: 0
    connectTime: 0.047
    nameLookupTime: 0.031
    preTransferTime: 0.047
    redirectCount: 0
    redirectTime: 0
    startTransferTime: 0.047
    totalTime: 0.047
```

Thanks!
